### PR TITLE
[RFR] Slide to desired item at mount

### PR DESCRIPTION
**Pull request by jpetitcolas**
Currently, we slide to `activeSlideKey` item only during the `componentDidUpdate` method. Yet, this method is not called during the initial render. This PR fixes that. 

My use case: I keep track of current slide in the URL. Hence, I retrieve the slide `key` based on the URL slug. Then, initial render already knows the active slide.

### CODE REVIEW

**Comment by mpartipilo** [comment]
I have just discovered this problem too. When do you plan to publish to npm?

**Comment by mpartipilo** [comment]
> My use case: I keep track of current slide in the URL. Hence, I retrieve the slide `key` based on the URL slug. Then, initial render already knows the active slide.

Similar case, I use it on a custom lightbox.

**Comment by IlimaVIP** [comment]
I've been looking for the solution for a while now. My case is: I need to activate other card when page loads. Active card can be on index 3 or 20 ...
Can anyone share the example code for this case with componentDidUpdate()?

**Comment by mpartipilo** [comment]
I published the npm package with this PR included: https://www.npmjs.com/package/@mootzy/react-id-swiper

**Comment by IlimaVIP** [comment]
Alright, I don't know why it's not working for me. Am I doing it right? I'm just still new to React, but it's still showing me the first slider

`class Swipe extends Component {
    constructor(props) {
        super(props);
        this.state = { 
            params: {
                effect: 'coverflow',
                grabCursor: true,
                centeredSlides: true,
                slidesPerView: 'auto',
                activeSlideKey: '1',
                coverflowEffect: {
                  rotate: 50,
                  stretch: 0,
                  depth: 100,
                  modifier: 1,
                  slideShadows: true
                }
              }
         }
    }

    componentDidUpdate(prevProps, prevState) {
        this.setState({
            params: {
                activeSlideKey: '5'
            }
        })
    }
   
    render() { 
        return ( 
            <Swiper {...this.state.params}>
                <div>1</div>
                <div>2</div>
                <div>3</div>
                <div>4</div>
                        ...
                <div>25</div>
            </Swiper>
         );
    }
}
 `

**Comment by mpartipilo** [comment]
`componentDidUpdate()` will be called after properties or state changes. Perhaps you should try `componentDidMount()`

**Comment by IlimaVIP** [comment]
Tried that as well, no change.

**Comment by mpartipilo** [comment]
hacky thing, but try this:
    `setTimeout(() => this.setState({ { params: { activeSlideKey: '5' } }), 500)`

**Comment by IlimaVIP** [comment]
Still no luck.

**Comment by mpartipilo** [comment]
I realize now that you’re throwing away the params state. Look at this: 
https://stackoverflow.com/questions/43040721/how-to-update-nested-state-properties-in-react#51136076

`this.setState(prevState => { params: { ...prevState.params, activeSlideKey: '5' } })`

I hope this one does it

**Comment by kidjp85** [comment]
Sorry guys, so busy recently. I will try my best to release newest version this week.

**Comment by IlimaVIP** [comment]
Any updates on this issue?

**Comment by mpartipilo** [comment]
This was fixed already.

**Comment by IlimaVIP** [comment]
I don't know why, but since then, I tried all type of stuff, and didn't work for me...

**Comment by IlimaVIP** [comment]
Basically I made it work with the goNext() function, but it kind of doesn't give me exactly what I need, it's just a dirty way of sliding to the particular card.

**Comment by Soul244** [comment]
I have same problem. activeSlideKey doesn't work. I set all params in state and change activeSlideKey in componentDidMount but nothing changed. Still loads first child element of list.

**Comment by IlimaVIP** [comment]
@Soul244 For me the answer on #199 solved my issue. Looks like I didn't provide the key='value' for each card. Is it same for you?

**Comment by Soul244** [comment]
@IlimaVIP Thanks, it's worked. Actually, i am using hard coded cards. So for React, i don't need to set key for cards. But okey, this thing needs this :) 

Ekran Alıntısı

**Comment by IlimaVIP** [comment]
Yes @Soul244 I had the same problem)) Everything was hard coded, I usually provide the key in the loop. I guess next we will know. And I hope nobody will struggle with this type of issues. All thanks to @kidjp85 and @kolyabokov

**Comment by edupleich** [comment]
Hey @IlimaVIP, did you also come up with a temporary work around for this problem?

**Pull request merged**
