### PR TITLE
Add jest. Expose rebuildSwiper instance method.

### PR DESCRIPTION
**Pull request by timkindberg**
So the main thing I needed was a way to manually trigger a swiper rebuild. So I added an instance method called `rebuildSwiper` which will destroy and create swiper. I refactored two places that were doing this to call this single new method.

I need access to this because I'm finding the rebuildOnUpdate and shouldSwiperUpdate props to be a bit limited for my use case. I need to be able to change the slidesPerView only when a device orientation event happens. So the children are not changing, only that single prop.

While I was at it I figured it would be good to have a test and realized no test runner was set up so I did that too :)

Also btw whenever I've tried turning on rebuildOnUpdate, the component becomes very buggy. I've not explored it more but I know it's related to that rebuildOnUpdate prop. I feel like in the future we could expose more fine-grained control on when the swiper should update, so instead of passing true/false for the rebuildOnUpdate and shouldSwiperUpdate you could pass a function that accepted prev/next props and returns a boolean. Future PR maybe :)

### CODE REVIEW

**Comment by timkindberg** [comment]
I just realized I didn't commit the build files... I'm not sure if I should have or how you handle those?

**Comment by kidjp85** [comment]
Hi @timkindberg , thanks for your commit. Please also commit the build file too.

**Comment by timkindberg** [comment]
Ok done!

**Comment by timkindberg** [comment]
When will this change be released?

**Pull request merged**
