### PR TITLE
1.6.7

### PR DESCRIPTION
**Pull request by kidjp85**

### CODE REVIEW

**Comment by connorsmallman** [comment]
Why has the styles folder been removed?

**Comment by connorsmallman** [comment]
Same, so I would expect it to be a major release as it's a breaking change. Although it looks more like we're using the repo incorrectly and should use the cdn for the styles

**Comment by crohrer** [comment]
There should be a way to import styles without using an external CDN. I can't load external resources because of GDPR

**Comment by crohrer** [comment]
Yes I could add the CSS manually, but the whole point of using npm is that I don’t have to do stuff like this manually. 
Up to version 1.6.6 I could just update my npm packages and the CSS was updated automatically. That’s why I think it’s not a good idea to remove the styles from this project. After all, the styles correspond to a certain version of the JS - which is bundled in the npm package.

**Pull request merged**
